template_chooser:
  enabled: true
  default_template: feature.md
  templates:
    - name: Feature Pull Request
      filename: feature.md
      about: Submit a new feature implementation
      labels: feature
    
    - name: Bug Fix Pull Request
      filename: bugfix.md
      about: Submit a bug fix
      labels: bug-fix
    
    - name: Documentation Pull Request
      filename: docs.md
      about: Submit documentation changes
      labels: documentation