name: 📖 Documentation/Website Change
description: Request changes to documentation or website content
title: "[Docs/Website] "
labels: ["documentation"]
assignees: []
projects: []
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists that is similar to your issue/suggestion.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Description
    description: |
      Describe the documentation or website change you're requesting. Include:
      * What needs to be changed?
      * Why it needs to be changed?
      * Any relevant context or references?
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Affected Areas
    description: Check all that apply
    options:
    - label: README.md
    - label: Getting_Started.md
    - label: API Documentation
    - label: Code Comments
    - label: UI Help Text
    - label: Other

- type: checkboxes
  attributes:
    label: Type of Update
    description: What kind of update is this?
    options:
    - label: New Documentation Needed
    - label: Incorrect Information
    - label: Missing Information
    - label: Clarity Improvement
    - label: Example Needed

- type: textarea
  attributes:
    label: Current Documentation
    description: If applicable, paste the existing text that you think needs improvement.
  validations:
    required: false

- type: textarea
  attributes:
    label: Proposed Changes
    description: What should the documentation say instead?

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any screenshots, references, or context for this suggestion. You can drag files into this box.
