name: 📈 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] <title>"
labels: ["feature"]
assignees: []
projects: []
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists that is similar to your request.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Problem Statement
    description: A clear and concise description of the problem this feature would solve.
    placeholder: Explain the current limitation or need.
  validations:
    required: true

- type: textarea
  attributes:
    label: Proposed Solution
    description: A clear and concise description of what you want to happen.
    placeholder: Describe your suggested implementation.
  validations:
    required: false

- type: textarea
  attributes:
    label: Alternative Solutions
    description: Any alternative solutions or features you've considered.
    placeholder: Describe other ideas you've thought about.
  validations:
    required: false

- type: textarea
  attributes:
    label: User Story
    description: Use the format "As a [user], I want [action] so that [value]".
    placeholder: As a [type of user], I want [an action] so that [benefit/value].
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: List of things that must be true for the feature to be considered complete.
    placeholder: |
      - [ ] Criterion 1
      - [ ] Criterion 2
      - [ ] Criterion 3
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context, mockups, or screenshots about the feature request here.
  validations:
    required: false
